### PR TITLE
Update Task.php

### PR DESCRIPTION
**Pull request by legoboy0215**
Just for those dumb eyes.

### CODE REVIEW

**Comment by legoboy0215** [comment]
Why??? Oh...

**Comment by xpyctum** [comment]
@legoboy0215  it is not necessary

**Comment by legoboy0215** [comment]
lol...

**Comment by legoboy0215** [comment]
But the === is better practice...

**Comment by xpyctum** [comment]
No, in this moment == is better.

**Comment by legoboy0215** [comment]
Ok.

**Comment by legoboy0215** [comment]
I invited you. Would you accept?

**Pull request closed without merging**
