### PR TITLE
Update Task.php

### PR DESCRIPTION
**Pull request by PEMapModder**

### CODE REVIEW

**Comment by PEMapModder** [comment]
What... Why `help`...

**Comment by xpyctum** [comment]
@PEMapModder Now your code is another. The plugin checks signs differently. It checks all the signs on the server. If I put your code, then changes back to version 1.0

**Comment by PEMapModder** [comment]
OK. But why `Help` label?

**Comment by xpyctum** [comment]
@PEMapModder  It is no longer active, but I'll take your Changes to your code :)

**Pull request closed without merging**
